### ISSUE TITLE
Erro ao iniciar docker

### ISSUE THREAD

**Issue by fdabrao** [fabinajm/docker-mssql#1]
Boa noite,

Quando tento iniciar com 
`docker-compose up`
apresenta
`dbaccess_1  | /bin/sed: can't read /opt/totvs/dbaccess/multi/dbaccess.ini: No such file or directory`
é normal?

**Comment by fabinajm** [comment]
> Boa noite,
> 
> Quando tento iniciar com
> `docker-compose up`
> apresenta
> `dbaccess_1 | /bin/sed: can't read /opt/totvs/dbaccess/multi/dbaccess.ini: No such file or directory`
> é normal?

O arquivo x caminho do dbaccess estava errado, isso foi ajustado um tempo atrás, tente novamente.
